project:
  type: website
  resources:
    - sign_vector_conditions/**

website:
  favicon: images/leaf-fill.svg
  # favicon: images/puzzle-fill.svg
  # title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
        # icon: house
      - publications.qmd
      - talks.qmd
      - software.qmd
      # - about.qmd

    right:
      - icon: envelope
        text: Email
        href: mailto:aichmayr@mathematik.uni-kassel.de
      - icon: github
        text: GitHub
        href: https://github.com/MarcusAichmayr
      - text: '<i class="ai ai-orcid"></i> Orcid'
        href: https://orcid.org/0009-0008-8362-2644
      - text: '<i class="ai ai-researchgate"></i> ResearchGate'
        href: https://www.researchgate.net/profile/Marcus-Aichmayr
      # - icon: file-earmark-person
      #   text: CV
      #   href: files/cv.pdf

format:
  html:
    theme:
      # darkly, superhero, solar, slate
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css:
    - styles.css
    - _extensions/schochastics/academicons/assets/css/size.css
    - _extensions/schochastics/academicons/assets/css/all.css
    toc: true
