project:
  type: website
  resources:
    - sign_vector_conditions/**

website:
  # title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - talks.qmd
      - software.qmd
      - text: CV TODO
        href: files/cv.pdf
      # - about.qmd

    right:
      - icon: github
        href: https://github.com/MarcusAichmayr
      - icon: orcid
        href: https://orcid.org/0009-0008-8362-2644
      - icon: envelope
        href: mailto:aichmayr@mathematik.uni-kassel.de
      - icon: researchgate
        href: https://www.researchgate.net/profile/Marcus-Aichmayr

format:
  html:
    theme:
      dark: superhero
      # darkly, superhero, solar, slate
      light: cosmo
    css: styles.css
    toc: true



