project:
  type: website
  resources:
    - sign_vector_conditions/**

website:
  # title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - talks.qmd
      - software.qmd
      # - about.qmd

    right:
      - icon: github
        href: https://github.com/MarcusAichmayr
      - text: '<i class="ai ai-orcid"></i>'
        href: https://orcid.org/0009-0008-8362-2644
      - icon: envelope
        href: mailto:aichmayr@mathematik.uni-kassel.de
      - text: '<i class="ai ai-researchgate"></i>'
        href: https://www.researchgate.net/profile/Marcus-Aichmayr
      - icon: file-earmark-person
        href: files/cv.pdf

format:
  html:
    theme:
      dark: superhero
      # darkly, superhero, solar, slate
      light: cosmo
    css:
    - styles.css
    - _extensions/schochastics/academicons/assets/css/size.css
    - _extensions/schochastics/academicons/assets/css/all.css
    toc: true
