---
title: "Publications"
---

### Submitted/Preprints

* M.S. Aichmayr, G. Regensburger
  <br>
  *Computing Circuits over Integral Domains*,
  <br>
  (2026), 14 pages. Submitted.
* M.S. Aichmayr
  <br>
  *SignVectors: a SageMath Package for Oriented Matroids*.
  <br>
  ISSAC'26, Software abstract,
  2026

### Peer-reviewed publications

* M.S. Aichmayr, S. Müller, G. Regensburger
  <br>
  *A SageMath Package for Elementary and Sign Vectors with Applications to Chemical Reaction Networks*
  <br>
  Proceedings of ICMS'24 (eds. K. Buzzard, A. Dickenstein, B. Eick, A. Leykin, Y. Ren), Lecture Notes in Comput. Sci. 14749, Springer, Cham, pp. 155-164, 2024.
  [DOI](https://doi.org/10.1007/978-3-031-64529-7_17) | [arXiv](https://arxiv.org/abs/2407.12660)

### Theses

* M.S. Aichmayr
  <br>
  *Computing Circuits and Sign Vectors with Applications to Linear Inequality Systems and Reaction Networks*.
  <br>
  PhD thesis, University of Kassel, Germany, 2026.
  [pdf TODO]
* M.S. Aichmayr
  <br>
  *Computing with sign vectors in SageMath and applications to exponential maps*.
  <br>
  Master's thesis, Johannes Kepler University Linz, Austria, 2021.
  [pdf](publications/2021thesis_m.pdf)
