---
title: "Presentations"
---

Here is a list of talks and posters I have given at conferences and seminars.
For my slides, I use a minimalistic style with few sentences and dark background.
The handouts are not meant to be self-contained.

### 2026

* *SignVectors: a SageMath Package for Oriented Matroids*
  <br>
  ISSAC'26, Oldenburg, Germany, July.
  [handout](talks/2026ISSAC.pdf)
* *Computing Sign Vector Conditions for Complex-Balanced Equilibria of Chemical Reaction Networks*
  <br>
  SCDDE'26, Hagenberg, Austria, July.
  [poster](talks/2026SCDDE.pdf)
* *Computing Circuits and Sign Vectors with Applications to Linear Inequality Systems and Reaction Networks*
  <br>
  PhD defense, Kassel, Germany, July.
  [handout](talks/2026disputation.pdf)

### 2025

* *Reaction networks with (generalized) mass-action kinetics: Sign vector conditions for the existence of a unique general equilibrium*
  <br>
  ACA'25, Heraklion, Crete/Greece, July.
  [handout](talks/2025ACA.pdf)
* *Computing Elementary Vectors over Integral Domains*
  <br>
  Fachtagung der Computeralgebra'25, Leipzig, Germany, June.
  [handout](talks/2025Fachtagung.pdf)
* *Sign Vector Conditions for Reaction Networks*
  <br>
  MoRN seminar software showcase, online, April.
  [see](https://github.com/MarcusAichmayr/sign_and_elementary_vector_applications)

### 2024

* *Certifying Solvability of Linear Inequality Systems with Elementary Vectors*
  <br>
  CASC'24, Rennes, France, September.
  [handout](talks/2024CASC.pdf)
* *A SageMath Package for Elementary and Sign Vectors with Applications to Chemical Reaction Networks*
  <br>
  ICMS'24, Durham, UK, June.
  [handout](talks/2024ICMS.pdf)
* *Computing Sign Vector Conditions for Complex-Balanced Equilibria of Chemical Reaction Networks*
  <br>
  DART'24, Kassel, Germany, April.
  [poster](talks/2026SCDDE.pdf)

### 2023

* *Computing sign vector conditions for existence and uniqueness of equilibria of chemical reaction networks*
  <br>
  ACA'23, Warsaw, Poland, July.
  [handout](talks/2023ACA.pdf)
* *Certifying solvability of linear inequality systems using elementary vectors*
  <br>
  Fachtagung der Computeralgebra'23, Hannover, Germany, June.
  [handout](talks/2023Fachtagung.pdf)
